import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/Footer";
import { website_title } from "@/utils/constant";
import Navbar from "@/components/ui/Navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import StyledComponentsRegistry from "@/utils/AntRegistry";
import Script from "next/script";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: website_title,
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <Script
        src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js"
        defer
      ></Script>
      <Script src="/script.js" id="script"></Script>
      <body>
        <SessionProvider session={session}>
          <StyledComponentsRegistry>
            <div className="max-w-[1600px] mx-auto ">
              <Navbar />
              {children}
            </div>

            <Footer />
          </StyledComponentsRegistry>
        </SessionProvider>
      </body>
    </html>
  );
}
