import Nav from "@/components/Nav";
import Footer from "@/components/ui/Footer";
import Sidebar from "@/components/ui/Sidebar";
import SessionProvider from "@/utils/SessionProvider";
import { website_title } from "@/utils/constant";
import { getServerSession } from "next-auth";
import { Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: website_title,
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <Script
        src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js"
        defer
      ></Script>
      <Script src="/script.js" id="script"></Script>
      <link rel="shortcut icon" href="/favicon.svg" type="image/x-icon" sizes="any" />
      <body className={poppins.className} >
        <SessionProvider session={session}>
          <Nav />
          <div className="grid md:grid-cols-[200px_1fr] ">
            <div className="flex-col justify-between hidden md:flex">
              <Sidebar />
            </div>
            <div className="h-[calc(100vh-60px)] overflow-x-auto">
              {children}
              <Footer />
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
